//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maytech.Quatrix.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maytech.Quatrix.Messages.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Quatrix account is not currently active. Speak to your administrator or contact Quatrix Customer Care.
        /// </summary>
        internal static string api_account_suspended {
            get {
                return ResourceManager.GetString("api_account_suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Quatrix domain is not registered.
        /// </summary>
        internal static string api_host_invalid {
            get {
                return ResourceManager.GetString("api_host_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to log in to this account, please contact your Administrator for assistance..
        /// </summary>
        internal static string api_login_not_allowed {
            get {
                return ResourceManager.GetString("api_login_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t move folder to itself.
        /// </summary>
        internal static string api_metadata_move_to_itself {
            get {
                return ResourceManager.GetString("api_metadata_move_to_itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current metadata is not directory.
        /// </summary>
        internal static string api_metadata_not_directory {
            get {
                return ResourceManager.GetString("api_metadata_not_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name parameter cannot be empty.
        /// </summary>
        internal static string api_new_name_param_null {
            get {
                return ResourceManager.GetString("api_new_name_param_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login credentials.
        /// </summary>
        internal static string api_not_logined {
            get {
                return ResourceManager.GetString("api_not_logined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is empty.
        /// </summary>
        internal static string api_parameter_password_empty {
            get {
                return ResourceManager.GetString("api_parameter_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should not exceed 64 characters.
        /// </summary>
        internal static string api_parameter_password_too_long {
            get {
                return ResourceManager.GetString("api_parameter_password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should contain at least 6 characters.
        /// </summary>
        internal static string api_parameter_passwortd_too_short {
            get {
                return ResourceManager.GetString("api_parameter_passwortd_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent metadata is not set!.
        /// </summary>
        internal static string api_parent_metadata_null {
            get {
                return ResourceManager.GetString("api_parent_metadata_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expire date should be later than the release date.
        /// </summary>
        internal static string api_share_invalid_expire {
            get {
                return ResourceManager.GetString("api_share_invalid_expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release date should be earlier than the expiry date.
        /// </summary>
        internal static string api_share_invalid_release {
            get {
                return ResourceManager.GetString("api_share_invalid_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to share.
        /// </summary>
        internal static string api_share_no_files {
            get {
                return ResourceManager.GetString("api_share_no_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No receivers specified.
        /// </summary>
        internal static string api_share_no_receivers {
            get {
                return ResourceManager.GetString("api_share_no_receivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authorization code.
        /// </summary>
        internal static string authorizaion_code_invalid {
            get {
                return ResourceManager.GetString("authorizaion_code_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization code required.
        /// </summary>
        internal static string authorization_code_required {
            get {
                return ResourceManager.GetString("authorization_code_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff end date can&apos;t be early then start date.
        /// </summary>
        internal static string diff_from_later_than_to {
            get {
                return ResourceManager.GetString("diff_from_later_than_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name param is empty!.
        /// </summary>
        internal static string directory_name_param_empty {
            get {
                return ResourceManager.GetString("directory_name_param_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection. Check your connection and try again..
        /// </summary>
        internal static string internet_not_connected {
            get {
                return ResourceManager.GetString("internet_not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for chunk size.
        /// </summary>
        internal static string invalid_chunk_size {
            get {
                return ResourceManager.GetString("invalid_chunk_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action is failed.
        /// </summary>
        internal static string operation_delete_failed {
            get {
                return ResourceManager.GetString("operation_delete_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder has zero size.
        /// </summary>
        internal static string operation_not_allowed_folder_zero_size {
            get {
                return ResourceManager.GetString("operation_not_allowed_folder_zero_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported authorization type.
        /// </summary>
        internal static string unsupported_authorizaion_type {
            get {
                return ResourceManager.GetString("unsupported_authorizaion_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user PIN.
        /// </summary>
        internal static string user_pin_invalid {
            get {
                return ResourceManager.GetString("user_pin_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User PIN required.
        /// </summary>
        internal static string user_pin_required {
            get {
                return ResourceManager.GetString("user_pin_required", resourceCulture);
            }
        }
    }
}
