//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maytech.Quatrix.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maytech.Quatrix.Messages.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection error occured. Please contact &quot;servicedesk@quatrix.it&quot;..
        /// </summary>
        internal static string api_connection_error_occured {
            get {
                return ResourceManager.GetString("api_connection_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such email in account.
        /// </summary>
        internal static string api_credential_incorrect {
            get {
                return ResourceManager.GetString("api_credential_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field.
        /// </summary>
        internal static string api_data_empty {
            get {
                return ResourceManager.GetString("api_data_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login data.
        /// </summary>
        internal static string api_data_invalid {
            get {
                return ResourceManager.GetString("api_data_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct email.
        /// </summary>
        internal static string api_email_invalid {
            get {
                return ResourceManager.GetString("api_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct Quatrix® name.
        /// </summary>
        internal static string api_host_invalid {
            get {
                return ResourceManager.GetString("api_host_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to log in to this account, please contact your Administrator for assistance..
        /// </summary>
        internal static string api_login_not_allowed {
            get {
                return ResourceManager.GetString("api_login_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already logined.
        /// </summary>
        internal static string api_logined {
            get {
                return ResourceManager.GetString("api_logined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory with this path not found.
        /// </summary>
        internal static string api_metadata_not_found {
            get {
                return ResourceManager.GetString("api_metadata_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not logined.
        /// </summary>
        internal static string api_not_logined {
            get {
                return ResourceManager.GetString("api_not_logined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email parameter is empty.
        /// </summary>
        internal static string api_parameter_email_empty {
            get {
                return ResourceManager.GetString("api_parameter_email_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is empty.
        /// </summary>
        internal static string api_parameter_password_empty {
            get {
                return ResourceManager.GetString("api_parameter_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too long.
        /// </summary>
        internal static string api_parameter_password_too_long {
            get {
                return ResourceManager.GetString("api_parameter_password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short.
        /// </summary>
        internal static string api_parameter_passwortd_too_short {
            get {
                return ResourceManager.GetString("api_parameter_passwortd_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is failed. Current data is not correct! (Exception code: 401).
        /// </summary>
        internal static string api_request_failed {
            get {
                return ResourceManager.GetString("api_request_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is null referer.
        /// </summary>
        internal static string api_request_null {
            get {
                return ResourceManager.GetString("api_request_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired.
        /// </summary>
        internal static string api_session_expired {
            get {
                return ResourceManager.GetString("api_session_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name param is empty!.
        /// </summary>
        internal static string directory_name_param_empty {
            get {
                return ResourceManager.GetString("directory_name_param_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local directory not exist!.
        /// </summary>
        internal static string directory_not_exist {
            get {
                return ResourceManager.GetString("directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension not correct.
        /// </summary>
        internal static string file_extension_not_correct {
            get {
                return ResourceManager.GetString("file_extension_not_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File this path does not exist.
        /// </summary>
        internal static string file_not_exist {
            get {
                return ResourceManager.GetString("file_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restore your internet connection.
        /// </summary>
        internal static string internet_not_connected {
            get {
                return ResourceManager.GetString("internet_not_connected", resourceCulture);
            }
        }
    }
}
